"use strict";
//conditional tests :
let car = "sabaru";
console.log("is car=='sabaru'?i predict true");
console.log(car == "sabaru");
console.log("is car=='honda'? i predict false");
console.log(car == "honda");
console.log("is car !='ford'?i prefer true");
console.log(car != 'ford');
console.log("is car !='sabaru' i prefer false");
console.log(car != 'sabaru');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car === 'Subaru'? I predict False.");
console.log(car === 'Subaru');
console.log("Is car !== 'honda'? I predict True.");
console.log(car !== 'honda');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car > 'honda'? I predict True.");
console.log(car > 'honda');
console.log("Is car < 'ford'? I predict False.");
console.log(car < 'ford');
console.log(car === "suzuki");
console.log(car === "brv");
console.log(car !== "rangerover");
console.log(car === "fortuner");
console.log(car != "vidz");
console.log(car == "honda");
